version: '3.8'
services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: 'node-exporter'
    deploy:
      resources:
        limits:
          memory: '256M'
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /proc/net:/host/proc/net:ro
      - /sys/class/net:/host/sys/class/net:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    network_mode: host
